apiVersion: v1
kind: Service

metadata:
    name: svc-simple-echo
spec:
    type: NodePort
    selector:
        app: simple-echo
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
      